window.recipes = [
    {Name: "Cucumber salad with spinach, red onion, Goulash, and Rice", 
    Protein: 'Goulash', 
    Vegetables: ['Cucumber', 'Spinach'],
    },
    {Name: "Asparagus, eggplant, Creamy shrimp, and Pasta", 
    Protein: 'Shrimp', 
    Vegetables: ['Eggplant'],
    },
    {Name: "Broccoli salad, corn, blueberries, Ground meat, and Baked potatoes ", 
    Protein: 'Ground meat', 
    Vegetables: ['Broccoli'],
    },
    {Name: "Cucumber, lettuce, tomato salad, Roasted chicken breast, and Mashed potatoes", 
    Protein: 'Chicken breast', 
    Vegetables: ['Cucumber', 'Lettuce', 'Cherry Tomato'],
    },
    {Name: "Tomato, onion, cilantro, cucumber salad, Stewed chicken tights, and Pasta with oven-roasted tomatoes, mozarella ",
    Protein: 'Chicken tights', 
    Vegetables: ['Cherry Tomato', 'Cucumber'],
    },
    {Name: "Roasted eggplants, Meatballs, and Creamy potatoes", 
    Protein: 'Ground meat', 
    Vegetables: ['Eggplant'],
    },
    {Name: "Baked mushrooms, Shrimp with spinach, and Quinoa", 
    Protein: 'Shrimp', 
    Vegetables: ['Mushrooms', 'Spinach'],
    },
    {Name: "Mango salad with lettuce, red onion Tuna cakes, and Pasta",
    Protein: 'Tuna', 
    Vegetables: ['Lettuce'],
    },
    {Name: "Pumpkin, carrot cream Salmon marinated with dill, garlic, olive oil, and Lentils", 
    Protein: 'Salmon', 
    Vegetables: ['Pumpkin', 'Carrot'],
    },
    {Name: "Neapolitan eggplants, Grilled salmon, and Mashed potatoes", 
    Protein: 'Salmon', 
    Vegetables: ['Eggplant'],
    },
    {Name: "Sautéed mushrooms with corn, Beef, and Rice",
    Protein: 'Beef', 
    Vegetables: ['Mushrooms'],
    },
    {Name: "Zuchini cream, Burger meat, and Red bean",  
    Protein: 'Burger meat', 
    Vegetables: ['Zuchinni'],
    },
    {Name: "Sauteed eggplant, zucchini , mushrooms, Pork with BBQ sauce, and Rice",
    Protein: 'Pork', 
    Vegetables: ['Eggplant', 'Zuchinni', 'Mushrooms'],
    },
    {Name: "Russian salad, Grilled pork, and Red bean", 
    Protein: 'Pork', 
    Vegetables: ['Carrot', 'Beet'],
    },
    {Name: "Lettuce, spinach, apple salad, Creamy shrimp, and Mashed potatoes",
    Protein: 'Shrimp', 
    Vegetables: ['Lettuce', 'Spinach'],
    },
    {Name: "Broccoli, cauliflower cream, Meatballs, and Rice", 
    Protein: 'Ground meat', 
    Vegetables: ['Broccoli', 'Cauliflower'],
    },
    {Name: "Lettuce salad, cherry tomato, corn, radish Goulash, and Mashed potatoes", 
    Protein: 'Goulash',
    Vegetables: ['Lettuce', 'Cherry Tomato', 'Radish'],
    },
    {Name: "Lettuce salad, avocado, tomato, onion, zuchinni, Stewed chicken tights, and Rice",
    Protein: 'Chicken tights', 
    Vegetables: ['Lettuce', 'Cherry Tomato', 'Zuchinni'],
    },
    {Name: "Lettuce salad, sautéed paprika, zucchini, red onion, nuts, Ground meat, and Rice", 
    Protein: 'Ground meat',
    Vegetables: ['Lettuce', 'Zuchinni'],
    },
    {Name: "Greek salad, Roasted chicken breast, and Creamy potatoes", 
    Protein: 'Chicken breast', 
    Vegetables: [ 'Cherry Tomato', 'Cucumber'],
    },
    {Name: "Peas, carrot salad with yogurt, mayonnaise , mustard dressing, Sardines, and Rice",
    Protein: 'Sardines',
    Vegetables: ['Carrot'],
    },
    {Name: "Tomato, pickle, feta cheese salad, Meatballs, and Pasta with oven-roasted tomatoes , mozarella ",
    Protein: 'Ground meat', 
    Vegetables: ['Cherry Tomato'],
    },
    {Name: "Baked cauliflower with spices, Stewed chicken tights, and Quinoa",
    Protein: 'Chicken tights', 
    Vegetables: ['Cauliflower'],
    },
    {Name: "Cauliflower cream with sautéed mushrooms, Pork with BBQ sauce, and Lentils",
    Protein: 'Pork', 
    Vegetables: [ 'Cauliflower', 'Mushrooms'],
    },
    {Name: "Zucchini cream, Beef, and Mashed potatoes", 
    Protein: 'Beef', 
    Vegetables: ['Zuchinni'],
    },
    {Name: "Lettuce, green apple, almonds, onion, cranberry salad with balsamic vinaigrette, Goulash, and Rice", Protein: 'Goulash',
    Vegetables: ['Lettuce'],
    },
    {Name: "Eggplant, leek, zucchini sautéed with cumin, Tuna cakes, and Lentils", 
    Protein: 'Tuna',
    Vegetables: ['Eggplant', 'Zuchinni'],
    },
    {Name: "Roasted pumpking with feta cheese, Sardines, and Red bean", 
    Protein: 'Sardines', 
    Vegetables: ['Pumpkin, Cucumber'],
    } 
]